Busines logic #4
Umnica/quizapp pull request #32
Opened 2023-09-16 16:55 UTC by Umnica

на проверку....
если скажешь что что-то не так, и можно что-то юзать всякие фичи spring
переделывать не буду. оно работает и нормально. Ток осталось сделать валидацию
ты кнш пиши, что не так, но переделывать не хочу))))

2023-09-16 17:20 UTC, Umnica commented
ой я перепутал входные данные... сейчас исправлю

2023-09-16 22:48 UTC, difiozy requested changes

2023-09-16 22:48 UTC, difiozy commented on src/test/java/com/vtortsev/quizapp/AnswerServiceIntegrationTest.java
> +@Transactional
А для чего тут транзакция?

2023-09-16 22:48 UTC, difiozy commented on src/test/java/com/vtortsev/quizapp/AnswerServiceIntegrationTest.java
> +class AnswerServiceIntegrationTest {
Это не интеграционный тест, он же не ходит в бд

2023-09-16 22:48 UTC, difiozy commented on src/test/java/com/vtortsev/quizapp/AnswerServiceIntegrationTest.java
> +        assertTrue(Valid.isValidText("Valid answer text"));
Для Valid должен быть написан отдельный класс тестов и проверять их там, тут нужно вызывать createAnswer и проверят что логика внутри него соответствует ожиданию

2023-09-16 22:51 UTC, difiozy commented on logs/app.log
Удали этот файл уже отсюда))

2023-09-16 22:54 UTC, difiozy commented on src/test/java/com/vtortsev/quizapp/CategoryServiceTests.java
> +        when(categoryDao.save(expectedCategory)).thenReturn(expectedCategory);
Тут ты возвращаешь тот же объект, это неправильно, нужно проверять состояния объектов, по логике вещей из dao у тебя должен вернуть объект с id после insert

2023-09-19 16:47 UTC, Umnica commented
я не знаю как удалить logs/app.log
30 раз его написал в gitignore, а он меня преследует
и папку, и сам файл...

2023-09-20 16:17 UTC, difiozy requested changes

2023-09-20 16:17 UTC, difiozy commented on src/test/java/com/vtortsev/quizapp/ValidTest.java
> +    }
Каждый вызов должен этого метода должен находиться в отдельном методе и из названия точно должно быть понятно что в нем

2023-09-20 16:17 UTC, difiozy commented on src/test/java/com/vtortsev/quizapp/ValidTest.java
> +    }
Этот тест должен находиться в другом классе, потому что этот у тебя называется ValidTest, а соответственно тестирует только util методы класса Valid

2023-09-20 16:17 UTC, difiozy commented on src/test/java/com/vtortsev/quizapp/ValidTest.java
> +    }
Помни про SOLID

2023-09-20 16:17 UTC, difiozy commented on src/test/java/com/vtortsev/quizapp/serviseTests/AnswerServiceTest.java
> +    private AnswerService answerService1;
Все Autowired должны быть вверху класса

2023-09-20 16:17 UTC, difiozy commented on src/test/java/com/vtortsev/quizapp/serviseTests/AnswerServiceTest.java
> +        Answer retrievedAnswer = answerService1.getAnswerById(savedAnswer.getId());
Тут я так понимаю должно выполниться сохранение в базу? Если да то так делать нельзя, нужно мокать дата слой

2023-09-20 16:17 UTC, difiozy commented on src/test/java/com/vtortsev/quizapp/serviseTests/QuestionServiceTest.java
> +    private CategoryService categoryService;
Аналогично, должны быть над всеми методами

2023-09-20 16:17 UTC, difiozy commented
Попробуй замержить в master только логику, без тестов, что бы мр стал меньше

2023-09-20 16:23 UTC, difiozy commented on src/main/java/com/vtortsev/quizapp/service/AnswerService.java
> +    public Answer createAnswer(Answer createAnswerDto) {
Здесть стоит либо имя переменной заменить, либо тип новый сделать, сейчас это не dto

2023-09-20 16:23 UTC, difiozy commented on src/main/java/com/vtortsev/quizapp/service/AnswerService.java
> +        answer.setQuestion(createAnswerDto.getQuestion());
Тут не нужно категории сохранять?

2023-09-20 16:57 UTC, merged